### ISSUE TITLE
Provide Pipfile to ease installation

### ISSUE THREAD

**Issue by hcw70** [Rolf-Hempel/PlanetarySystemStacker#19]
Since this great package depends on various other packages, it may be hard 
for others to install this on their OS since the OS typically comes with a set of 
pre-selected packages and version, which may reveal missing or wrong versions.

To solve this problem the python community has invented venv / virtual environments, which allow 
to easily reproduce your package / version setup on a different os in a private folder.

One tool (the currently best approach) would be pipenv, see https://realpython.com/pipenv-guide/ for a quick guide.

If you could fix / publish your package / version setup by providing your Pipfile, it would be a breeze to try out the SW.

Regards

**Comment by Rolf-Hempel** [comment]
Hi Hauke,

Thanks for pointing me at this interesting way to distribute Python code. I have never heard of "pipenv" before, so I had a look at the quick guide.

So far I did not work on the portability issues of the PlanetarySystemStacker project myself. Other people wrote "recipes" for various Linux flavors which you can find in Appendix B of the [User's Guide](https://github.com/Rolf-Hempel/PlanetarySystemStacker/blob/master/Documentation/PlanetarySystemStacker_User-Guide.pdf). It would be great to add a section there with a detailed explanation how to install PSS using pipenv. We could add the Pipfile to the ressources of the next release.

Since you seem to be familiar with pipenv, would you be willing to try that out and write the text for the Appendix?

All the best,
 Rolf

**Comment by hcw70** [comment]
Hi Rolf. It would be a pleasure for me to try out as soon as you have a pipfile.... 8->

Regards
Hauke

**Comment by hcw70** [comment]
Ok i have read Appendix B now. 
The problem there is the same as i have. 
> The following instructions were tested using Xubuntu 18.04 LTS 64bit and Debian 10.1.0

So i have 19.10, so i will get different package versions than what you / they used to test. 
Some newer packages may break api compatibility.

Pipenv will solve that problem.

**Comment by Rolf-Hempel** [comment]
Hi Hauke,

Meanwhile I discussed the pipenv issue with the colleague who wrote the Appendix B "recipes". He is investigating the issue. If all works well he will come up with a pipfile that we would publish here with the next release.

All the best,
 Rolf

**Comment by Plutonium5793** [comment]
Hi Hauke,
I am the guy from appendix b.  Since you suggested trying pipenv, I have been spending some time trying to make an environment.  While I have been able to make environments that contain python 3.7, I have not had any success getting the environment to load the dependencies.  It seems that the Pipfile just needs the list of dependencies but I have given put the list from appendix b in the pipfile, and I don't seem to be able to get it to install them.   You sound like you are more familiar with pipenv than I and I would appreciate any tips you have to get PSS installed in this manner.  I do have another concern that the environment once made does not seem to be able to be copied to other computers.  In my mind that means each user would have to through this installation.   
Also I would like to assure you that today I installed ubuntu 19.1 on a computer and ran the directions for 18.04 from the PSS instructions, and PSS runs fine on 19.1 using those directions.  
Thanks for any help you can give me in moving forward with an installation using pipenv.

**Comment by alexhelms** [comment]
I suggest you look into virtual environments. You should never be doing python development outside of a virtual environment set up specifically for the project or else you will run into the "it works on my machine" problems like you have here.

I'm going to list below my steps on getting this working in a fresh install of ubuntu 19.10 in a vm:

```
cd ~
sudo apt install python3-venv python3-dev git
python3 -m venv pss
source pss/bin/activate
pip install --upgrade pip
cd ~/Documents
git clone git://github.com/Rolf-Hempel/PlanetarySystemStacker.git
nano requirements.txt
```
At this point I filled requirements.txt with the following:
```
opencv-python==4.1.2.30
matplotlib==3.1.2
psutil==5.6.7
PyQt5==5.14.1
scipy==1.4.1
astropy==4.0
scikit-image==0.16.2
```
And now back to getting it working:
```
pip install -r requirements.txt
python3 Source/planetary_system_stacker.py
```

Now I ran into a bit of trouble with mkl. `pip install mkl` doesnt seem to work in my vm. 
```
pip install https://files.pythonhosted.org/packages/9b/98/c892b77b755cb0c53491eabc88c49451a92e36fa5c5baf578e77b91ee31d/mkl-2019.0-py2.py3-none-manylinux1_x86_64.whl
```
Gives me an error about it isnt supported on my platform...which is odd because it is python3, linux, x64.

Either way, hope this helps. You should also look into using a `pyproject.toml` and being PEP518 compliant.

**Comment by Plutonium5793** [comment]
Hi Alex,
To my knowledge we are not having difficulties with our current method at this time.  The ubuntu 18.04 installation works just fine on 19.1 as I have verified it on a plain vanilla copy.  Hauke is suggesting we use pipdev and what you have outlined above is the (older?) pip method.  Since I am finding a learning curve with either, I am not sure which way to go.  I will try to duplicate what you have outlined, but have a concern about mkl not working.  
My other concern is that these containers are not portable (as far as I have been able to find; please correct me if I am wrong. ).  If they are not portable, then each user is going to have to go through this installation which seems just as complicated as the appendix b method.  If we do run into version control issues (which seem to me to be avoidable if the package keeps up to date with its versions).  Another possibility would be to retry other containerization methods such as AppImage or one of the others discussed earlier on the CloudyNight forums.  
Anyway I will try to duplicate your installation today, and get back with the results.  Thank you for outlining your method in detail, and I am hoping to get something similar from Hauk so I can test out pipdev also.  I do realize your requirements.txt might will be very similar to what I need for a pipfile so I will also be trying that.   Again, thanks for your input,
John

**Comment by hcw70** [comment]
> Hi Alex,
> To my knowledge we are not having difficulties with our current method at this time. The ubuntu 18.04 installation works just fine on 19.1 as I have verified it on a plain vanilla copy. Hauke is suggesting we use pipdev and what you have outlined above is the (older?) pip method.

To me it is less important if you use `python -m venv` or `pipenv`. However, since pipenv seems to be the way to go, i suggested that method. I am however more used to using `python -m venv`.

The big difference to me seems to be that pipenv manages indirect dependencies better (or at all ) as opposed to   `python -m venv`. This may be the reason for the issue @alexhelms gets.
 
> Since I am finding a learning curve with either, I am not sure which way to go. I will try to duplicate what you have outlined, but have a concern about mkl not working.

IMHO pipenv is the superiour approach.

> My other concern is that these containers are not portable (as far as I have been able to find; please correct me if I am wrong. ). If they are not portable, then each user is going to have to go through this installation which seems just as complicated as the appendix b method. 

The containers are not portable. The point of them is to have an user / app specific installation of required packages in an user / app specific folder. 

>If we do run into version control issues (which seem to me to be avoidable if the package keeps up to date with its versions). Another possibility would be to retry other containerization methods such as AppImage or one of the others discussed earlier on the CloudyNight forums.

If a pipfile / requirements.txt is provided, that contains / should contain proper version info of all used packages, so that makes the installation reproducible in the first place and make your app OS-independent. 

> Anyway I will try to duplicate your installation today, and get back with the results. Thank you for outlining your method in detail, and I am hoping to get something similar from Hauk so I can test out pipdev also. I do realize your requirements.txt might will be very similar to what I need for a pipfile so I will also be trying that. Again, thanks for your input,
> John

Regards

Hauke

**Comment by Plutonium5793** [comment]
Ok, what I understand from this discussion, is that all we need to provide you a list of the versions of dependencies that the program uses and then you (the user) can build the container in your flavor of linux.  From then on out, you would maintain the container.   In the "about PSS" box of the software, many of the versions used are currently listed right now.  I am sure that we can provide a complete list as a text file for those who wish to containerize their installation.  
Rolf, if you are reading this, I think we only need to provide a text file for all the versions you are using for all the dependencies listed in appendix B.  PSS currently lists these in the 'about PSS' window
Python 3.7.6, Qt: 5.13.2, Matplotlib 3.1.2, OpenCV: 3.4.8, Numpy 1.16.4
It looks like we need to add version numbers for: psutils, scipy, astropy, scikit-image, pip, git, and mkl.

**Comment by alexhelms** [comment]
It is more than just a list of dependencies. It is a standardized file that is used by automated tools when packaging up a library/application. There are a few standards, ie. requirements.txt, pyproject.toml, and pipfile, but they are all flavors of the same thing -- allowing you to create reproducible builds that contain all the dependencies for a specific platform. Linux, windows, etc. use different python wheels when there are C extensions, like with scipy or mkl. I strongly suggest you research how python dependency management and application deployment work.

**Comment by alexhelms** [comment]
The mkl issue was caused by pip 20.0.1 ... good job pip team.
```
pip install pip==19.3.1
pip install mkl
```
Works just fine, as it should have.

**Comment by Plutonium5793** [comment]
I am trying to be humorous when I point out that your version control had a version control problem. ;-)
I get what you are saying but do you think it would be better for me (who has yet to make a successful pipfile) design the pipfile rather that either of you who already use them.  From what I understand, the list of dependencies is the major part of the pipfile or requirements.txt.  It just needed to be formatted to fit the requirements of the container.  Perhaps you could format a working one that I could try out to verify it works on various linux platforms.  Seeing one that works I might well be able to produce another in the future.
John

**Comment by hcw70** [comment]
> Ok, what I understand from this discussion, is that all we need to provide you a list of the versions of dependencies that the program uses and then you (the user) can build the container in your flavor of linux.

Exactly

> I am sure that we can provide a complete list as a text file for those who wish to containerize their installation.

Yes, but the point here is to provide that text file in a form that some of the virtualenv python tools can read / process it already. Proposal was pipenv therefore.

Kind regards

Hauke

**Comment by Plutonium5793** [comment]
Rolf has provided me with a complete list of versions.  

![](https://www.cloudynights.com/uploads/monthly_01_2020/msg-258431-0-58036000-1579878832.png)

If you can provide me with a working Pipfile, it can be put online or in the documentation so people can use it.  I can also test it against various flavors of linux, to ensure that it works properly in each.

**Comment by Rolf-Hempel** [comment]
Meanwhile we have decided to write detailed instructions how to install Python 3 on a Linux machine and then download PSS from here. (Thanks to John Duchek for trying this on several Linux flavors and writing the User Guide Appendix.) This seems to work quite well on a variety of Linux distributions.
