### ISSUE TITLE
PSS and SER format (16-Bit Mono) trouble

### ISSUE THREAD

**Issue by selste** [Rolf-Hempel/PlanetarySystemStacker#25]
Hi,
i've run into trouble processing 16-Bit SER files acquired with [AstroDMx Capture](https://www.linux-astro-imaging.uk/linux/astronomy/astrodmx-capture-overview).
PSS simply fails to read these files, output on the console is:

> Error in opening / reading frames: Error in reading first video frame, continuing with next job

No trouble at all opening SER files created by FireCapture 2.6

As a quick check i then installed [SER Player](https://sites.google.com/site/astropipp/ser-player) which is included in the Debian Repository (starting with 'Buster', i think), the package name is simply 'ser-player'.
The application had no problem at all opening and playing both files.
I also had a quick look at both files using a HEX editor (Midnight Commander), and it seems that there are differences in the headers.
Could You have look into this - i'd be happy to provide sample files, maybe help (if possible, i'm not an expert when it comes to programming in Python).
Cheers,

Steffen

**Comment by selste** [comment]
Forgot to mention, running on Debian Testing, PSS info:

System overview:
CPU Cores: 3
Memory: 2.9 [GB]
OS: Linux 5.4.0-4-amd64 64bit

Software versions used:
Python: 3.8.2
Qt: 5.12.5
Matplotlib: 3.1.2
OpenCV: 4.2.0
Numpy: 1.17.4
Psutil: 5.6.7
Scipy: 1.3.3
Scikit-image: 0.16.2
Astropy: 4.0
Pip: 20.0.2

**Comment by Rolf-Hempel** [comment]
Hi Steffen,

It is really a mess that developers of camera capturing software don't adhere to the SER standard. After all, it is not that complicated. Most frequent is the deviation that the first 14 characters are not "LUCAM-RECORDER", but their own company name.

It would be good if you could provide me access to a short sample video. It does not need to have more than a few frames. Then I will look into this issue.

All the best,
 Rolf

**Comment by selste** [comment]
Hello Rolf,
well, i had a quick look at the latest spec and - again - at a file created by AstroDMx Capture ... and the SER file starts with 'AstroDMx' :-(
I've created a repository where You can have a look yourself: [astrodmx-sample](https://github.com/selste/astrodmx-sample) - no celestial content, sorry, just the garden.

I'll send a bug report to the developers - hopefully they'll fix this.
Cheers,

Steffen

**Comment by Rolf-Hempel** [comment]
Hello Steffen,

I agree that it is a good idea to tell those guys that the SER header is not the place for advertising. Anyway, I will look at it. If this is the only non-conformity I will add the AstroDMx header as valid in the SER parser. I did the same for another capturing software provider. This way the files will pass the test in the next PSS release.

I just don't want to ignore the first 14 characters of the SER header because otherwise the file could contain anything which PSS could not make use of, and it would be difficult to know if it is supposed to be a SER file at all.

All the best,
 Rolf

**Comment by selste** [comment]
Hi Rolf,
totally agree - the header is there for a purpose.

If i'm not misinterpreting the specs the fixed FileID was only introduced with version 3 (together with additional color format codes and other stuff).
Maybe the developers simply weren't aware of the changes ... i'll keep You posted.
Cheers,

Steffen

**Comment by Rolf-Hempel** [comment]
Hi Steffen,

I changed the SER parser such that a non-conformity in the first 14 characters is reported as a warning instead of an error. Here is a sample screenshot:

![grafik](https://user-images.githubusercontent.com/19596791/79434905-4fae4400-7fcf-11ea-88ee-3a52a2e1889b.png)

I think this problem is the most frequent non-conformity. So, changing the program behaviour this way solves most problems. The new code will become part of the next release.

All the best,
 Rolf
