### ISSUE TITLE
python version requirement

### ISSUE THREAD

**Issue by danielhampf** [Rolf-Hempel/PlanetarySystemStacker#26]
Hello,
I just tried to install PSS via pip, but it told me the only acceptable python versions are 3.5 and 3.6. However, I've recently upgraded to python 3.7 and I don't really want to downgrade again. I know, there are virt-env etc, but is this restriction really necessary at all? More and more people will move to python 3.7, 3.8 etc.
Thank you!
DH

**Comment by Rolf-Hempel** [comment]
Hi,
The problem is not PSS itself, but the "astropy" package it depends on. This package does not work with Python 3.7 or 3.8. There is a way to get it fixed, as you can read in [this post on Cloudy Nights](https://www.cloudynights.com/topic/645890-new-stacking-software-project-planetarysystemstacker/?p=10180691). But I did not want to tell users that they should go this way because it would have caused lots of questions.

You don't need to downgrade your Python 3 version for any other purpose, since you can have more than one Python 3 installation on your computer. I know that this is not a convenient solution, but as long as the astropy people don't fix their problem, I do not see any other way to deal with this issue.

Interestingly, on Linux and MacOS this problem does not exist.

All the best, 
 Rolf
