### ISSUE TITLE
Windows Installer: Wrong path for start menu shortcut

### ISSUE THREAD

**Issue by daenuprobst** [Rolf-Hempel/PlanetarySystemStacker#27]
Instead of "planetary_system_stacker.exe", the shortcut in the Windows start menu points to "planetary_system_stacker_exe".

https://github.com/Rolf-Hempel/PlanetarySystemStacker/blob/f0a406d4c0218fbf2fbff1754e45fbeec62553f8/InstallForge/InstallForge_1-4-1.ifp#L325

**Comment by Rolf-Hempel** [comment]
Hi Daniel,

Thanks for pointing me at this bug. You are right!

I changed the IstallForge specification file. I tried to run Pyinstaller again in order to create a new installer file, but I could not start the created executable. So I gave up on procuding a new installer file for version 0.8.0. The new start menu entry will be corrected with the next PSS release.

All the best,
 Rolf

**Comment by daenuprobst** [comment]
Thanks Rolf,

I wish I was as fast at handling issues ;-). Thanks a lot for the software and have a nice weekend.

Daniel
