### ISSUE TITLE
Problems stacking jupiter

### ISSUE THREAD

**Issue by pauladam316** [Rolf-Hempel/PlanetarySystemStacker#36]
Hi there,

Not sure if this is the best place to put it, but I'm having issues with stacking a drift version of jupiter. I'm using default settings with the frame stabilization mode set to planet. The issue is that when I start the job and arrive at the stacking frame it seems that it has failed to properly rank and detect the planet within the frame. Here is a screenshot of the issue

![image](https://user-images.githubusercontent.com/10899113/103304493-c57c0380-49d6-11eb-9c23-be8bf6e68642.png)

Is this a user error or a problem with the software? Is there anything I can do to remedy it?

**Comment by Rolf-Hempel** [comment]
Hi,

Could you please set the "protocol detail level" at 2, rerun the example without pressing "cancel" until PSS decides to finish the job, and post the protocol file? From the screenshot I cannot see what the problem is.

How does the video look like? What do you mean with "drift version of Jupiter"? If the planet drifts through the entire field of view, PSS cannot handle the frame stabilization. The program assumes that there is some dark space around the planet at any time.

All the best,
 Rolf

**Comment by pauladam316** [comment]
Hi Rolf,

Looks like your second point was right. The video is of jupiter passing across the camera sensor over about a minute, and while it starts in view at the end it does drift out of frame. Cropping those last few seconds seem to have resolved the issue.
