### ISSUE TITLE
Issue installing PSS on MacOs

### ISSUE THREAD

**Issue by sajalm96** [Rolf-Hempel/PlanetarySystemStacker#43]
Hi, 

I want to begin by stating I do not have any experience using python, but I am an amateur astronomer/astrophotographer and came across PSS. I followed the user guide, and the instructions within. After downloading Python3, I entered the command "pip3 install planetary-system-stacker" and the downloading initiated however, it gets perpetually stuck at "Building wheel for opencv-python-headless (PEP 517) ..." 
 
I am not entirely sure what I am doing wrong, but I've tried to look it up online and tried some of the solutions. I will be sincerely grateful if my query could be addressed, and once again, I am a complete beginner so it's very much possible I am missing something completely basic.

**Comment by Rolf-Hempel** [comment]
Hi,

This sounds like a problem with the Python installation on your system, not with PSS. On "Cloudy Nights" there have been lot of discussions on installation problem caused by different OS and Python versions. More specifically, in [this thread](https://www.cloudynights.com/topic/753290-planetarysystemstacker-installation-issues/) we discuss installation problems like yours. I suggest that you state your problem there with more details, e.g. the OS version used, the Python version number etc. Perhaps some other user has had a similar experience and has a solution at hand.

All the best,
 Rolf
