### ISSUE TITLE
[solved] This Old Mac (OSX 10.13 High Sierra) Install Difficulties 

### ISSUE THREAD

**Issue by dannafe** [Rolf-Hempel/PlanetarySystemStacker#49]
I have an old Macintosh (MacOS 10.13 High Sierra) that I use for Astrophotography and had difficulties getting PSS installed.
The following worked for me:
` sudo -H pip install --upgrade pip setuptools wheel ;
  sudo -H pip3 install opencv-python-headless==3.4.13.47 ;
  sudo -H pip3 install planetary-system-stacker ;
  PlanetarySystemStacker &
  `

**Comment by Rolf-Hempel** [comment]
Thank you very much for sharing your experience! I'm not familiar with MacOS, so I cannot help at all. That's a pity since especially Mac users seem to welcome PSS as a stacking software which not only works for Windows. So much more I'm glad that users like you help each other in getting around installation issues on the various Mac versions.
