### ISSUE TITLE
Wrong center of gravity for blurred frame

### ISSUE THREAD

**Issue by shushamen** [Rolf-Hempel/PlanetarySystemStacker#5]
Hi I am getting weird cog values with some videos that were taken with a cellphone and then produce a exception ( align_frames.py , average_frame method, align_frame_mode = "Planet")

Frame size is  ( shape  1080, 1920)  , but the  center_of_mass function returned 479815, 844872
cog_real = ndimage.measurements.center_of_mass(
                self.frames.frames_mono_blurred(self.frame_ranks_max_index))
Intersection, y_low: 470866, y_high: -27915820, x_low: 829103, x_high: -49230221

Then in the average_frame method I got :

 File "C:\Users\shushamen\source\repos\PlanetarySystemStacker-prototype\Source\align_frames.py", line 421, in average_frame
    dtype=float32)
ValueError: negative dimensions are not allowed 

 If I change line 207 to : 
cog_real = ndimage.measurements.center_of_mass(
                self.frames.frames_mono(self.frame_ranks_max_index))

and line 247 to 
frame = self.frames.frames_mono(idx) 

I got a descent stacked image

I tried with Surface align method and with main_program it finished but using the UI, the program got stuck in some infinite loop in alignment phase 

I think the problem is related to :
# Compute a version of the frame with Gaussian blur added.
            frame_monochrome_blurred = GaussianBlur(frame_mono,
                (self.configuration.frames_gauss_width, self.configuration.frames_gauss_width), 0)

any ideas ?

**Comment by Rolf-Hempel** [comment]
No, I don't have any idea what could have happened. Please note that this software is not released yet, and the "prototype" branch is in intensive dvelopment. I cannot even guarantee that at a given time the software is working properly with my test input files. Therefore, if you run the software, you do it at your own risk.

I do not know how your input videos look like. E.g. do they really show a planetary disk surrounded by dark sky? Otherwise the alignment method "planet" cannot work. It is very strange that the OpenCV routine "Gaussian Blur" method does not work properly. The fix you tried in the end cannot be the solution because the blur is essential for the algorithm to work. I would suggest that in a debugger you check the input image array before the cv2 call to find out if it fits with that library routine.

**Comment by shushamen** [comment]
ok thanks for the feedback, I will continue working on it and report the progress in case I do manage to find something

**Comment by jscheidtmann** [comment]
I had a similar problem. This is fixed in the prototype branch. Problem in the released version is, that the calculation of the center (of mass) on which aligning frames depends, returns values outside the image. 

The respective fix is to convert to a different type in these [two](https://github.com/Rolf-Hempel/PlanetarySystemStacker/blob/prototype/Source/align_frames.py#L207) [lines](https://github.com/Rolf-Hempel/PlanetarySystemStacker/blob/prototype/Source/align_frames.py#L253), when calculating the center_of_mass (note the conversion to float32).

The algorithm uses gray scale images to calculate the center of mass of the images. This basically is an average computation, which is sensitive to outliers (noise in the image). I therefore created a pull request (#8), which instead converts the image into a binary black and white image (using a user supplied cut off).

**Comment by Rolf-Hempel** [comment]
Hi,

I just changed the computation of the planetary frame alignment as proposed by Jens. The error should not occur any more.

All the best,
 Rolf
