### ISSUE TITLE
PSS does not finish when started from the command line

### ISSUE THREAD

**Issue by ostlight** [Rolf-Hempel/PlanetarySystemStacker#52]
Hi Rolf,

I would like to use PSS from the command line. I have done some tests similar to the following:

`python3 planetary_system_stacker.py directory_with_fits -p -b 4 -s 20 -a 52 -w 20 --normalize_bright --drizzle 1.5x`

However, PSS does not finish in my tests but hangs after

`+++ Start saving the stacked image +++`

As far as I can trace it, it is because in ConfigurationParameters in configuration.py 

`self.global_parameters_include_postprocessing = True`

is set. Since postprocessing is apparently not supported on the command line, I think that in setup_configuration in PssConsole 

`self.configuration.global_parameters_include_postprocessing = False`

must be set. In my case it fixes the problem but maybe you have a better solution.

**Comment by Rolf-Hempel** [comment]
Hi ostlight,

Thank you very much for pointing me to this problem! In fact I recently changed the standard behaviour because GUI users wished to have "stacking plus postprocessing" as the default. I changed the configuration line to "True" and did not notice that this would break the command line mode. 

Since I don't want to disappoint the GUI users again, I kept the configuration default to be "True". I solved the command line mode problem by overriding the "stacking plus postprocessing" option to "False" in the pss_console module. I think that this is the best way to handle the problem.

The bug fix will be part of the next release (0.9.2).

Thanks again for your help!

Best regards,
 Rolf
