### ISSUE TITLE
Error in reading video frame: last frame of an ffmpeg generated file

### ISSUE THREAD

**Issue by rnclark-psi** [Rolf-Hempel/PlanetarySystemStacker#68]
I am a big fan of PlanetarySystemStacker.  I run on linux mint I9 system with 128 GB ram) and have large files from a Canon R5.  PlanetarySystemStacker works fine on mp4 output directly from the camera.  However, I have a case where at the beginning and end of the video, the image was shaking.  PlanetarySystemStacker seemed to hang using 12 threads 99% cpu for hours.  So I extracted a clip of 20680 frames using ffmpeg.  and converted to a lossless avi file.

PlanetarySystemStacker gets the following error message at the end of Rank of all frames (the last frame):

Error in reading video frame, index:20680.
Try to convert the video with PIPP into some standard format,
continuing to next job

I have tried several different formats feeding to PlanetarySystemStacker with ffmpeg output and it always fails on the last frame.  I tried other shorter mp4 video files that I have, all with the same result: fine out of camera, but fails on the last frame for ffmpeg output.

I can supply example files if you wish.

Roger Clark

**Comment by Rolf-Hempel** [comment]
Hi Roger,

Dealing with video formats is a nightmare! I did not write any code for that purpose myself but rely on the opencv package (which under the hood uses ffmpeg). If opencv issues an exception in reading a frame, I catch it and tell the user that something is wrong with the video file.

Frankly speaking I don't want to delve deeper into this topic. I know that there are software products to correct broken video files. My experiences with PIPP are very good for that matter. That is why in the error message I suggest to use PIPP.

You wrote that the files produced by your camera work fine with PSS, and you just wanted to drop two blocks of frames at the beginning and end of the video because the camera was shaking (which otherwise caused PSS to hang in the image stabilization phase). Why don't you drop the frame blocks in PSS itself? To do so,, you have to check the parameter "dialog to exclude frames from stacking" in the "Frame-related Parameters" section. In the dialog which appears before the image stabilization phase you can drop single or entire blocks of frames. Would that be a solution in your case?

All the best,
 Rolf
